name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: test-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
          restore-keys: |
            test-${{ runner.os }}-gradle-
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: JDK 11 Install
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew --version
          ./gradlew build sonarqube -x functionalTest --parallel --info
      - name: Functional Test (Gradle 7)
        run: ./gradlew functionalTest --parallel
      - name: Functional Test (Gradle 5)
        run: ./gradlew functionalTest --parallel -Dgradle5=true
      - name: Functional Test (Gradle 6)
        run: ./gradlew functionalTest --parallel -Dgradle6=true

  publish_snapshot_artifacts:
    name: Publish Snapshot Artifacts
    needs: linux
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && github.repository == 'ciscoo/cxf-codegen-gradle' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/dists
          key: assemble-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
          restore-keys: |
            assemble-${{ runner.os }}-gradle-
      - name: JDK 11 Install
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew publish -x check

  update_snapshot_documentation:
    name: Update Snapshot Documentation
    needs: linux
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && github.repository == 'ciscoo/cxf-codegen-gradle' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/dists
          key: assemble-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
          restore-keys: |
            assemble-${{ runner.os }}-gradle-
      - name: JDK 11 Install
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Publish Snapshot Documentation'
        env:
          GRGIT_USER: ${{ secrets.GH_TOKEN }}
        run: .github/workflows/maybePublishSnapshotDocs.sh
