name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: test-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
          restore-keys: |
            test-${{ runner.os }}-gradle-
      - name: Test
        run: |
          ./gradlew --version
          ./gradlew build

  update_snapshot_documentation:
    name: Update Snapshot Documentation
    needs: linux
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && github.repository == 'ciscoo/cxf-codegen-gradle' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/dists
          key: assemble-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
          restore-keys: |
            assemble-${{ runner.os }}-gradle-
      - name: JDK 15 Install
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: 'Publish Snapshot Documentation'
        env:
          GRGIT_USER: ${{ secrets.GH_TOKEN }}
        run: .github/workflows/maybePublishSnapshotDocs.sh
